### PR TITLE
Evernote Data Saved to Database, API Usage Reduced by 50%, and more

### PR DESCRIPTION
**Pull request by holycrepe**
1. All Evernote data saved to database
2. Since Tags are saved locally, we don't need to query Evernote for them. This reduces API usage by 50%
3. Notes that are already in sync with Evernote's servers won't update
4. Generate Anki deck name from Evernote notebook name
5. Anknotes detects links between notes and creates table of contents pages for linked notes. This is an advanced function that will likely require some documentation before it can be widely used by the general public.

### CODE REVIEW

**Comment by holycrepe** [comment]
Hey, I made some significant changes to the Models (Note Types) used by anknotes. I haven't tested to see if they are automatically generated without errors so there may be some issues with that. However, if you manually setup the Models, it works flawlessly. 

I'll look into automating initial setup of the Models if there's interest. In the more distant future, I will write up some documentation about how to use the Table of Contents functionality, which is very useful if you have lots of notes that are interconnected, and you utilize Evernote's Note Links to link between notes.

**Comment by Scriptkiddi** [comment]
hey looks great I will test it and then merge it

**Comment by holycrepe** [comment]
I just pushed some important changes: I was able to fix the problem with generating the new Models, and it works perfectly. I'd still recommend you initially test this release on a new profile though, just in case anything gets corrupted. 

Also I added an option to change the error handling to tooltips instead of message boxes, and added a timer to automatically import notes (default 15 minute intervals). Since the addon now ignores notes that are already up-to-date, you can effectively import your entire collection by starting the timer and leaving Anki open. The only hitch is I've noticed is, if you start the timer, the process sometimes stays open even after you quit Anki. So for now if you use the timer be prepared to force-quit the anki.exe process after manually closing Anki.

The last thing for me to do is make it so the Anki notes save the updatedSequenceNumber, instead of just saving it into the database. That way we don't incorrectly think the note is updated if a crash occurs after saving the note into the database but before adding the Anki note

**Comment by holycrepe** [comment]
@brumar take a note of this too

**Comment by holycrepe** [comment]
Oh also, you're going to want to either delete the existing "evernote_note" Model/Note Type so that anknotes can re-add the updated version, or manually add the new fields. You can view the other models or the source code to see the new fields

**Comment by holycrepe** [comment]
Made some more changes to the note models, so you'll want to delete or manually update the note models if you've already started testing the recent commits. The updatedSequenceNumber is now saved in the Anki note, so anknotes will detect whether or not a note is in sync with Evernote's servers.

Paging has been enabled so that you can set up > 250 notes to be downloaded (that is the upper limit returnable by Evernote API's findNoteMetadata call. An option was added to Evernote's preferences. 

Unfortunately the auto timer is not working. The only way I could get a timer set up with Python was to use threading. But that's no good because Anki is set up to not allow multiple threads to access the sqlite db. I've tried to get around this in many ways but to no avail. Are you aware of either a non-threading method of setting up a timer, or a way to get Anki to allow the db to shared amongst threads?

Otherwise, I think the code is perfect and probably represents a 1.0 version that is ready for public release. Other than any unforeseen bugs while you guys test the code, I don't think I'll be making any code changes any time soon. I'll try my best to add some documentation in the coming months, but in the meantime, if you guys have any questions feel free to ask.

**Comment by Scriptkiddi** [comment]
@holycrepe 
So sorry that it took me so long it looks like when you reworked the toc hierarchy you removed generateTocTitle in favor of EvernoteNoteTitle.FullTitle but im not sure about that so you still have refrences to the removed generateTocTitle

**Pull request merged**
